stages:
  preprocess:
    cmd: python src/data/preprocessing.py
    deps:
      - data/raw/raw.csv
      - src/data/preprocessing.py
    outs:
      - data/processed

  normalize:
    cmd: python src/data/normalize.py
    deps:
      - data/processed
      - src/data/normalize.py
    outs:
      - data/processed_scaled

  gridsearch:
    cmd: python src/models/gridsearch.py
    deps:
      - data/processed_scaled
      - src/models/gridsearch.py

  train:
    cmd: python src/models/train_model.py
    deps:
      - data/processed_scaled
      - src/models/train_model.py

  evaluate:
    cmd: python src/models/evaluate_model.py
    deps:
      - data/processed_scaled
      - src/models/evaluate_model.py
    outs:
      - data/predictions.csv
      - metrics/accuracy.json
